# Experiment 8
## Tools or EDA - Study of Numpy Library
## Name - Kshitij Dalvi
## PRN - 25070123066
## Batch - A3

In [ ]:
# why numpy ?
# faster than lists

In [ ]:
# Declaration of numpy
import numpy as np
a = np.array([10,20,30,40])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Dimension of array
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
# Find out shape of array
print(a.shape)
print(b.shape)

(4,)
(2, 3)


In [ ]:
# Find out data type of array
print(a.dtype)
print(b.dtype)

int64
int64


In [ ]:
# In Built functions using numpy
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# Creates symmetric matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Creates diagonal matrix
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
print(b*2)
print(a+5)
print(a)
print(b)

[[ 2  4  6]
 [ 8 10 12]]
[15 25 35 45]
[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Mean of array
print(np.mean(a))
print(np.mean(b))

25.0
3.5


In [ ]:
# Median of array (when median and mean are same, you have no outliers and data is clean. But when their difference is large, the data is not clean )
print(np.median(a))
print(np.median(b))

25.0
3.5


In [ ]:
# Find maximum
print(np.max(a))
print(np.max(b))

40
6


In [ ]:
# Find minimum
print(np.min(a))
print(np.min(b))

10
1


In [ ]:
# Find sum
print(np.sum(a))
print(np.sum(b))

100
21
